// Code generated by "stringer -type=FieldTypeRefKind -trimprefix=FieldType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldTypeIdent-0]
	_ = x[FieldTypeSelector-1]
	_ = x[FieldTypePtr-2]
	_ = x[FieldTypeArray-3]
	_ = x[FieldTypeMap-4]
	_ = x[FieldTypeStruct-5]
}

const _FieldTypeRefKind_name = "IdentSelectorPtrArrayMapStruct"

var _FieldTypeRefKind_index = [...]uint8{0, 5, 13, 16, 21, 24, 30}

func (i FieldTypeRefKind) String() string {
	if i < 0 || i >= FieldTypeRefKind(len(_FieldTypeRefKind_index)-1) {
		return "FieldTypeRefKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldTypeRefKind_name[_FieldTypeRefKind_index[i]:_FieldTypeRefKind_index[i+1]]
}
